env:
  global:
    - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3.7
matrix:
  include:
    - python: 3.7
addons:
  apt:
    packages:
      - jq
      - bash
      - curl
      - tree
      - docker-ce
      - libxml2-utils
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable
      - python3-setuptools
      - python3-pip
services: xvfb
install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  #
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 5432 8080 8081 8082 8083 8084 8085 8086 8087 8088
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip -V
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade httpie
  - http --version --debug
  - pip -V
  #
  - stop_any 80 3000 8000 8080
script:
  - ./gradlew
  - bash ./build/libs/*.jar &
  - wait_for 8080
  - http :8080
  - http :8080/api/data
  - http :8080/path-not-found accept:text/html
  - stop_any 80 3000 8000 8080
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.local/daggerok
